Initialisation du style et du README pour la surcharge DSFR RTL
GouvernementFR/dsfr-rtl pull request #1
Opened 2024-11-18 15:52 UTC by GautierLa

2024-11-21 14:30 UTC, zellerbaptiste commented on README.md
> +Il est possible de télécharger les sources de ce repository au format .zip depuis [la page Release de Github](https://github.com/GouvernementFR/dsfr-rtl/releases). Le fichier compilé se trouve dans `
```suggestion
Il est possible de télécharger les sources de ce repository au format .zip depuis [la page Release de Github](https://github.com/GouvernementFR/dsfr-rtl/releases). Le fichier compilé se trouve dans `dist/dsfr-rtl.css`, ou `dist/dsfr-rtl.min.css` pour la version minifiée. Vous trouverez aussi une version sass `src/dsfr-rtl.scss` paramètrable via des variables, permettant de paramétrer les classes utilitaires à générer.
```

2024-11-21 14:32 UTC, zellerbaptiste commented on README.md
> +* Les **textes non-traduits** dans un texte RTL peuvent avoir un comportement non désiré s'il y a des nombres ou des caractères spéciaux en début ou fin de phrase. Il est possible de résoudre cette p
👍

2024-11-25 13:28 UTC, zellerbaptiste requested changes

2024-11-25 13:28 UTC, zellerbaptiste commented on src/dsfr-rtl.scss
> +// ) !default;
Retirer les commentaires inutiles

2024-11-25 13:28 UTC, zellerbaptiste commented on src/dsfr-rtl.scss
> +  @media (min-width: 36em) {
Utiliser la variable `$breakpoints` pour les valeurs des media-queries.

2024-11-25 13:28 UTC, zellerbaptiste commented on src/dsfr-rtl.scss
> +  // Range
Ajouter l'inversion des préfixe et suffixe

2024-11-25 13:28 UTC, zellerbaptiste commented on src/dsfr-rtl.scss
> +  // Range
![Capture d’écran 2024-11-25 à 11 20 12](https://github.com/user-attachments/assets/4f3dca28-89b8-47c1-9f86-8a47d9b44529)

2024-11-25 13:28 UTC, zellerbaptiste commented on src/dsfr-rtl.scss
> +  // Consent manager
Corriger l'affichage du carret du bouton de collapse dans la modale de consentement : 
![Capture d’écran 2024-11-25 à 11 25 14](https://github.com/user-attachments/assets/4b04d1ce-06e1-48f0-b5eb-cf8c5496cdcb)
![Capture d’écran 2024-11-25 à 11 26 30](https://github.com/user-attachments/assets/7682a709-f481-4dca-85cb-589335de04b2)

2024-11-25 13:28 UTC, zellerbaptiste commented on src/dsfr-rtl.scss
> +  // Tabs
Corriger l'ombre au scroll sur les onglets qui doit s'afficher des 2 cotés si besoin (ici uniquement à droite) : 
![Capture d’écran 2024-11-25 à 11 30 38](https://github.com/user-attachments/assets/d69fc000-f1b6-4dc7-817a-5af51541b696)

2024-11-25 13:28 UTC, zellerbaptiste commented on src/dsfr-rtl.scss
> +  // Table
Les checkboxes des tableaux selectionnables ne sont plus centrées : 
![Capture d’écran 2024-11-25 à 11 35 18](https://github.com/user-attachments/assets/7f005bca-dcbf-48d1-a3eb-79a94337875f)

2024-11-25 14:55 UTC, keryanS commented on src/dsfr-rtl.scss
> +// ) !default;
Ces variables sont modifiables donc documentées

2024-11-25 16:12 UTC, keryanS commented on src/dsfr-rtl.scss
> +  // Tabs
Correction à effectuer sur le js du composant -> 1.13

2024-11-25 16:54 UTC, zellerbaptiste commented on src/dsfr-rtl.scss
> +  // Table
deja géré 👍

2024-11-25 16:57 UTC, keryanS commented on src/dsfr-rtl.scss
> +  // Table
Iso dsfr, la cellule s'étend en fonction du container.

2024-11-28 08:40 UTC, zellerbaptiste approved these changes

2024-12-04 14:25 UTC, keryanS approved these changes

2024-12-04 14:29 UTC, merged